# python scripts/eval/benchmark_recon.py -cn diffusercam
#
# To sweep over multiple hyperparameters, e.g. of mu1 and mu2 of ADMM:
# python scripts/eval/benchmark_recon.py -cn diffusercam -m algorithms=[ADMM] n_iter_range=[10,100] admm.mu1=1e-6,1e-5 admm.mu2=1e-6,1e-5 admm.mu3=3e-5 admm.tau=1e-4
#
# Hydra will do a Cartesian product of mu1 and mu2, i.e. it will run 4 experiments.
# Output will be saved to `multirun` folder.
defaults:
  - defaults
  - _self_

dataset: HFDataset
batchsize: 4
device: "cuda:0"

huggingface:
  repo: "bezzam/DiffuserCam-Lensless-Mirflickr-Dataset-NORM"
  psf: psf.tiff
  image_res: null
  rotate: False   # if measurement is upside-down
  alignment: null
  downsample: 2
  downsample_lensed: 2
  flipud: True
  flip_lensed: True 
  single_channel_psf: True

algorithms: [
  "ADMM",
  "ADMM_PnP",
  "FISTA",
  "FISTA_PnP",

  ## -- reconstructions trained on DiffuserCam measured
  # "hf:diffusercam:mirflickr:U5+Unet8M",
  # "hf:diffusercam:mirflickr:Unet8M+U5",
  # "hf:diffusercam:mirflickr:TrainInv+Unet8M",
  # "hf:diffusercam:mirflickr:MMCN4M+Unet4M",
  # "hf:diffusercam:mirflickr:MWDN8M",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M",
  # "hf:diffusercam:mirflickr:Unet4M+TrainInv+Unet4M",
  # "hf:diffusercam:mirflickr:Unet2M+MMCN+Unet2M",
  # "hf:diffusercam:mirflickr:Unet2M+MWDN6M",
  # "hf:diffusercam:mirflickr:Unet4M+U10+Unet4M",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_psfNN",

  # ## comparing UNetRes and Transformer, ADAMW optimizer
  # "hf:diffusercam:mirflickr:Transformer4M+U5+Transformer4M",
  # "hf:diffusercam:mirflickr:Transformer4M+U5+Transformer4M_psfNN",
  # "hf:diffusercam:mirflickr:U5+Transformer8M",
  # "hf:diffusercam:mirflickr:U5+Unet8M_adamw",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_adamw",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_psfNN_adamw",

  # # -- benchmark PSF error
  # "hf:diffusercam:mirflickr:U5+Unet8M_psf0dB",
  # "hf:diffusercam:mirflickr:U5+Unet8M_psf-5dB",
  # "hf:diffusercam:mirflickr:U5+Unet8M_psf-10dB",
  # "hf:diffusercam:mirflickr:U5+Unet8M_psf-20dB",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_psf-0dB",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_psf-5dB",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_psf-10dB",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_psf-20dB",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_psfNN_psf-0dB",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_psfNN_psf-10dB",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_psfNN_psf-20dB",

  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_ft_tapecam",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_ft_tapecam_post",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_ft_tapecam_pre",

  # ## -- reconstruction trained on DiffuserCam simulated
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_tapecam",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_tapecam_post",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_tapecam_pre",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_digicam_multi_post",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_digicam_multi_pre",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_digicam_multi",
  
  # ## -- reconstructions trained on other datasets/systems
  # "hf:tapecam:mirflickr:Unet4M+U10+Unet4M",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U5+Unet4M_wave",
  # "hf:digicam:celeba_26k:Unet4M+U5+Unet4M_wave",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M_psfNN",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U10+Unet4M_wave",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U5+Unet4M_wave_psfNN",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M_flips",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M_flips_rotate10",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M_aux1",
  # "hf:digicam:mirflickr_multi_25k:Unet4M+U10+Unet4M_wave",
  # "hf:digicam:mirflickr_multi_25k:Unet4M+U5+Unet4M_wave",
]

save_idx: [0, 1, 3, 4, 8]
n_iter_range: [10]    # for ADMM
# save_idx: [0, 1, 3, 4, 8, 45, 58, 63]
# n_iter_range: [100]    # for ADMM

admm:
  mu1: 1e-6
  mu2: 1e-5
  mu3: 4e-5
  tau: 0.0001

